### ISSUE TITLE
feat: 거리에 따른 프로세스 처리 뷰

### ISSUE THREAD

**Issue by SEOKJUN-KO** [SEOKJUN-KO/FinlandSauna#7]
## 🛠 Issue

거리 값에 따라, 사용자 위치 변환
하단 탭으로 작업사항 표시
가까워지면, NFC 자동 활성화
작업 처리 시, 하단 탭에서 사라짐

## 📝 To-do

- [ ] 거리 값에 따라, 사용자 위치 변환
- [ ] 하단 탭으로 작업사항 표시
- [ ] 가까워지면, NFC 자동 활성화
- [ ] 작업 처리 시, 하단 탭에서 사라짐
